//! Protobuf definitions (generated by `prost-build`).
//!
//! The `.proto` sources live in `proto/` and are compiled at build time.

pub mod iothub {
    include!(concat!(env!("OUT_DIR"), "/_.rs"));
}

